# Generated by Django 5.1.4 on 2024-12-15 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_alter_habit_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PleasantHabit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Описание действия приятной привычки",
                        max_length=255,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "is_reward",
                    models.BooleanField(
                        default=True,
                        help_text="Является ли эта привычка способом вознаградить себя за выполнение полезной привычки",
                        verbose_name="Признак вознаграждения",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Пользователь, который создает приятную привычку",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Приятная привычка",
                "verbose_name_plural": "Приятные привычки",
            },
        ),
        migrations.CreateModel(
            name="Reward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Описание вознаграждения, которое пользователь получит",
                        max_length=255,
                        verbose_name="Описание вознаграждения",
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Стоимость вознаграждения (если применимо)",
                        max_digits=10,
                        null=True,
                        verbose_name="Стоимость вознаграждения",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Пользователь, который получит вознаграждение",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вознаграждение",
                "verbose_name_plural": "Вознаграждения",
            },
        ),
        migrations.CreateModel(
            name="UsefulHabit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Описание действия, которое будет выполнено в рамках привычки",
                        max_length=255,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "time",
                    models.TimeField(
                        help_text="Время, когда необходимо выполнять привычку",
                        verbose_name="Время выполнения",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        help_text="Место, где будет выполняться привычка",
                        max_length=255,
                        verbose_name="Место выполнения",
                    ),
                ),
                (
                    "periodicity",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Периодичность повторения привычки (по умолчанию 1 день)",
                        verbose_name="Периодичность (в днях)",
                    ),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(
                        help_text="Ожидаемое время на выполнение привычки в секундах",
                        verbose_name="Время выполнения (в секундах)",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Может ли привычка быть опубликована для других пользователей?",
                        verbose_name="Публичность",
                    ),
                ),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Приятная привычка, которая будет связана с этой полезной привычкой",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habits.pleasanthabit",
                        verbose_name="Связанная привычка",
                    ),
                ),
                (
                    "reward",
                    models.ForeignKey(
                        blank=True,
                        help_text="Вознаграждение, которое пользователь получит за выполнение привычки",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habits.reward",
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Пользователь, который создает привычку",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Полезная привычка",
                "verbose_name_plural": "Полезные привычки",
            },
        ),
        migrations.AddField(
            model_name="pleasanthabit",
            name="related_useful_habit",
            field=models.ForeignKey(
                blank=True,
                help_text="Полезная привычка, с которой связана эта приятная привычка",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="habits.usefulhabit",
                verbose_name="Связанная полезная привычка",
            ),
        ),
        migrations.DeleteModel(
            name="Habit",
        ),
    ]
